"use strict";
/* ============ CONTENIDO CURADO DEL CURSO DE IDIOMAS (perfil adulto) ============ */
/* Banco fijo que funciona SIN clave de Gemini (igual que el resto de la app: IA si hay clave,
   banco local si no). El vocabulario de inglés se cruzó contra listas abiertas de nivel CEFR
   (openlanguageprofiles/olp-en-cefrj, MIT/CC) como referencia de curación, no como dependencia
   en vivo — nada se descarga de GitHub en tiempo de ejecución. Alemán/portugués/italiano son
   un punto de partida curado a mano; Gemini enriquece todo dinámicamente cuando hay clave. */

/* cada palabra/expresión: [frase en el idioma, español, ejemplo de uso, truco para memorizarla,
   traducción al español del ejemplo — para que la frase nunca use palabras que el estudiante
   todavía no conoce sin explicación] */
const LANG_VOCAB_SEED={
 en:{
  saludos:[["Hello","Hola","Hello! How are you?","Suena parecido a 'jelou', muy fácil de recordar.","¡Hola! ¿Cómo estás?"],
   ["Good morning","Buenos días","Good morning, everyone!","'Morning' se parece a 'mañana' del inglés antiguo — piénsalo como 'buen momento'.","¡Buenos días a todos!"],
   ["How are you?","¿Cómo estás?","How are you today?","'How' suena a 'jau', como si preguntaras '¿jau te va?'.","¿Cómo estás hoy?"],
   ["Nice to meet you","Mucho gusto","Nice to meet you, I'm Kate.","'Nice' = lindo/agradable, o sea 'agradable conocerte'.","Mucho gusto, soy Kate."],
   ["See you later","Nos vemos luego","See you later, bye!","Literal: 've-te más tarde' — imagina despedirte con la mano.","Nos vemos luego, ¡chao!"],
   ["Goodbye","Adiós","Goodbye, have a good day!","Viene de 'God be with you' — como decir 'que Dios te acompañe'.","Adiós, ¡que tengas un buen día!"]],
  compras:[["How much is it?","¿Cuánto cuesta?","How much is this shirt?","'How much' = 'cuánto', pregunta directa de precio.","¿Cuánto cuesta esta camisa?"],
   ["Receipt","Recibo","Can I have the receipt, please?","Suena a 'risít' — imagina que 're-citas' el precio pagado.","¿Me da el recibo, por favor?"],
   ["Cash","Efectivo","I'll pay in cash.","'Cash' suena a 'cache' de dinero guardado.","Voy a pagar en efectivo."],
   ["Credit card","Tarjeta de crédito","Do you accept credit card?","Casi igual que en español, fácil de reconocer.","¿Aceptan tarjeta de crédito?"],
   ["Discount","Descuento","Is there a discount today?","Se parece a 'descuento' — 'dis' + 'cuenta'.","¿Hay descuento hoy?"],
   ["Shopping cart","Carrito de compras","I need a shopping cart.","'Shopping' = comprar, 'cart' = carreta.","Necesito un carrito de compras."]],
  trabajo:[["Meeting","Reunión","We have a meeting at 3pm.","Suena a 'mitin' (como los mítines políticos = reuniones).","Tenemos una reunión a las 3pm."],
   ["Deadline","Fecha límite","The deadline is Friday.","'Dead' (muerto) + 'line' (línea) = la línea que no puedes cruzar.","La fecha límite es el viernes."],
   ["Colleague","Colega","My colleague sent the email.","Casi igual a 'colega' en español.","Mi colega envió el correo."],
   ["Email","Correo electrónico","Check your email.","Palabra que ya usamos igual en español.","Revisa tu correo."],
   ["Schedule","Horario","What's your schedule today?","Suena a 'eskédiul' — imagina un horario 'es-que-di-lo'.","¿Cuál es tu horario hoy?"],
   ["Boss","Jefe","My boss is very kind.","Corta y fácil, suena como 'bos'.","Mi jefe es muy amable."]],
  comida:[["Water","Agua","Can I have some water?","Suena a 'wáter' — el mismo sonido que usamos para el baño en español (agua/water).","¿Me da un poco de agua?"],
   ["Bread","Pan","I'd like some bread.","'Bred' suena parecido a 'breve', piensa en pan recién horneado.","Quisiera un poco de pan."],
   ["The bill, please","La cuenta, por favor","Excuse me, the bill please.","'Bill' = cuenta, como la 'factura' en inglés.","Disculpe, la cuenta por favor."],
   ["Delicious","Delicioso","This soup is delicious!","Casi idéntica al español.","¡Esta sopa está deliciosa!"],
   ["Allergic to","Alérgico a","I'm allergic to nuts.","'Allergic' se parece mucho a 'alérgico'.","Soy alérgico a las nueces."],
   ["Table for two","Mesa para dos","A table for two, please.","Literal: 'mesa para dos', fácil de armar.","Una mesa para dos, por favor."]],
  viajes:[["Airport","Aeropuerto","The airport is far.","'Air' (aire) + 'port' (puerto) = puerto del aire.","El aeropuerto está lejos."],
   ["Ticket","Boleto","Where is my ticket?","Palabra que ya usamos igual en español.","¿Dónde está mi boleto?"],
   ["Luggage","Equipaje","My luggage is heavy.","Suena a 'lógueich' — imagina que 'cargas' tu equipaje.","Mi equipaje pesa mucho."],
   ["Passport","Pasaporte","I need my passport.","Casi idéntica al español.","Necesito mi pasaporte."],
   ["Where is...?","¿Dónde está...?","Where is the hotel?","'Where' suena a 'uer', pregunta de lugar.","¿Dónde está el hotel?"],
   ["How much time?","¿Cuánto tiempo?","How much time until we arrive?","Combina 'how much' + 'time' (tiempo).","¿Cuánto tiempo falta para llegar?"]],
  emergencias:[["Help!","¡Ayuda!","Help! Call someone!","Corta y directa, fácil de gritar si hace falta.","¡Ayuda! ¡Llama a alguien!"],
   ["Call the police","Llama a la policía","Please, call the police.","'Police' se parece mucho a 'policía'.","Por favor, llama a la policía."],
   ["I need a doctor","Necesito un médico","I need a doctor now.","'Doctor' es casi igual en los dos idiomas.","Necesito un médico ahora."],
   ["Fire!","¡Fuego!","Fire! Get out!","Corta, suena a 'fáiar' — piensa en 'fire' de disparar/encender.","¡Fuego! ¡Sal de aquí!"],
   ["I'm lost","Estoy perdido","Excuse me, I'm lost.","'Lost' suena a 'lost' de la serie — perdido en la isla.","Disculpe, estoy perdido."],
   ["Ambulance","Ambulancia","Call an ambulance!","Casi idéntica al español.","¡Llama una ambulancia!"]],
  familia:[["Mother","Madre","This is my mother.","Suena a 'mader', parecida a 'madre' en el sonido.","Esta es mi madre."],
   ["Father","Padre","My father works a lot.","Se parece a 'padre' con una 'f' en vez de 'p'.","Mi padre trabaja mucho."],
   ["Brother","Hermano","I have one brother.","Viene de la misma raíz que 'fraternal' en español.","Tengo un hermano."],
   ["Sister","Hermana","My sister is younger than me.","Se parece a 'sorority', hermandad de mujeres.","Mi hermana es menor que yo."],
   ["Children","Hijos","We have two children.","Piensa en 'children's' de las tiendas de ropa infantil.","Tenemos dos hijos."],
   ["Husband","Esposo","My husband is a doctor.","Corta, suena a 'jasband' — imagina 'ese hombre es mi esposo'.","Mi esposo es médico."],
   ["Grandmother","Abuela","My grandmother lives with us.","'Grand' (grande) + 'mother' (madre) = la madre grande.","Mi abuela vive con nosotros."]],
  salud:[["Doctor","Doctor","I need to see a doctor.","Idéntica al español.","Necesito ver a un médico."],
   ["Appointment","Cita","I have an appointment at 3pm.","Suena a 'apóintment' — imagina 'apuntar' una cita en la agenda.","Tengo una cita a las 3pm."],
   ["Headache","Dolor de cabeza","I have a headache.","'Head' (cabeza) + 'ache' (dolor) = dolor de cabeza.","Tengo dolor de cabeza."],
   ["Medicine","Medicina","Take this medicine twice a day.","Casi idéntica al español.","Toma esta medicina dos veces al día."],
   ["Pharmacy","Farmacia","The pharmacy is open.","Se parece a 'farmacia', solo cambia la 'f' por 'ph'.","La farmacia está abierta."],
   ["I feel sick","Me siento mal","I feel sick today.","'Sick' suena a 'sik' — piensa en alguien enfermo en cama.","Me siento mal hoy."],
   ["Fever","Fiebre","She has a fever.","Se parece a 'fiebre' en el sonido inicial.","Ella tiene fiebre."]],
  tecnologia:[["Phone","Teléfono","My phone is broken.","Corta, viene de 'telephone' sin el 'tele'.","Mi teléfono está roto."],
   ["Computer","Computadora","I work on my computer.","Casi idéntica al español.","Trabajo en mi computadora."],
   ["Password","Contraseña","I forgot my password.","'Pass' (pasar) + 'word' (palabra) = palabra para pasar.","Olvidé mi contraseña."],
   ["Internet","Internet","The internet is slow.","Idéntica en todos los idiomas.","El internet está lento."],
   ["App","Aplicación","Download this app.","Abreviación de 'application', igual que en español.","Descarga esta aplicación."],
   ["Charger","Cargador","Do you have a charger?","'Charge' = cargar, viene de la misma raíz.","¿Tienes un cargador?"],
   ["Wifi","Wifi","What's the wifi password?","Idéntica en todos los idiomas.","¿Cuál es la contraseña del wifi?"]],
  clima:[["Sunny","Soleado","Today is sunny.","'Sun' = sol, 'sunny' = con mucho sol.","Hoy está soleado."],
   ["Rainy","Lluvioso","It's rainy outside.","'Rain' = lluvia, fácil de asociar.","Está lloviendo afuera."],
   ["Cold","Frío","It's very cold today.","Corta y directa, suena a 'cold' de 'helado'.","Hace mucho frío hoy."],
   ["Hot","Caliente","It's hot in summer.","Muy corta, suena igual en casi cualquier idioma que la use prestada.","Hace calor en verano."],
   ["Umbrella","Paraguas","Bring an umbrella.","Se parece a 'sombrilla' en el sonido final.","Trae un paraguas."],
   ["Snow","Nieve","It's snowing.","Corta, suena a 'esnóu' — piensa en 'snowboard'.","Está nevando."],
   ["Wind","Viento","There's a lot of wind.","Se parece a 'windsurf', deporte con viento.","Hay mucho viento."]]
 },
 de:{
  saludos:[["Hallo","Hola","Hallo, wie geht's?","Suena casi como 'halo' en español, fácil de recordar.","Hola, ¿cómo estás?"],
   ["Guten Morgen","Buenos días","Guten Morgen! Hast du gut geschlafen?","'Guten' = bueno, 'Morgen' = mañana, literal 'buena mañana'.","¡Buenos días! ¿Dormiste bien?"],
   ["Wie geht's?","¿Cómo estás?","Hallo, wie geht's?","'Wie' = cómo (suena 'vi'), 'geht's' = va.","Hola, ¿cómo estás?"],
   ["Freut mich","Mucho gusto","Freut mich, dich kennenzulernen.","'Freut' viene de alegrarse — 'me alegra' conocerte.","Me alegra conocerte."],
   ["Bis später","Hasta luego","Bis später, tschüss!","'Bis' = hasta, 'später' = después/tarde (como 'tarde' en inglés 'later').","Hasta luego, ¡chao!"],
   ["Auf Wiedersehen","Adiós","Auf Wiedersehen, bis morgen!","Literal: 'hasta volver a ver' — un adiós formal.","Adiós, ¡hasta mañana!"]],
  compras:[["Wie viel kostet das?","¿Cuánto cuesta?","Wie viel kostet das Brot?","'Kostet' se parece a 'costó' en español.","¿Cuánto cuesta el pan?"],
   ["Quittung","Recibo","Kann ich die Quittung haben?","Suena a 'kvitung' — piensa en 'quitar' la cuenta pendiente.","¿Me puede dar el recibo?"],
   ["Bargeld","Efectivo","Ich zahle mit Bargeld.","'Bar' (en efectivo) + 'Geld' (dinero) = dinero en mano.","Pago en efectivo."],
   ["Kreditkarte","Tarjeta de crédito","Akzeptieren Sie Kreditkarte?","Casi idéntica al español, fácil de reconocer.","¿Aceptan tarjeta de crédito?"],
   ["Rabatt","Descuento","Gibt es einen Rabatt?","Corta y parecida a 'rebate' en inglés.","¿Hay descuento?"],
   ["Einkaufswagen","Carrito de compras","Ich brauche einen Einkaufswagen.","'Einkauf' = compra, 'Wagen' = carro — 'carro de compra'.","Necesito un carrito de compras."]],
  trabajo:[["Besprechung","Reunión","Wir haben eine Besprechung.","Larga pero suena a 'hablar sobre algo' (besprechen = discutir).","Tenemos una reunión."],
   ["Frist","Fecha límite","Die Frist ist Freitag.","Corta, suena a 'frist' de 'first' — el primer límite.","La fecha límite es el viernes."],
   ["Kollege/Kollegin","Colega","Mein Kollege hat die E-Mail geschickt.","Casi idéntica a 'colega' en español.","Mi colega envió el correo."],
   ["E-Mail","Correo electrónico","Sende mir eine E-Mail.","Igual que en español.","Envíame un correo."],
   ["Zeitplan","Horario","Wie ist dein Zeitplan?","'Zeit' = tiempo, 'Plan' = plan — 'plan de tiempo'.","¿Cuál es tu horario?"],
   ["Chef/Chefin","Jefe","Mein Chef ist nett.","Igual a la palabra francesa 'chef', fácil de recordar.","Mi jefe es amable."]],
  comida:[["Wasser","Agua","Kann ich Wasser haben?","Suena a 'váser' — parecido a 'water' en inglés.","¿Me da agua?"],
   ["Brot","Pan","Ich möchte Brot.","Corta, suena a 'brot' como 'broa' de pan.","Quisiera pan."],
   ["Die Rechnung, bitte","La cuenta, por favor","Die Rechnung, bitte!","'Rechnung' viene de 'rechnen' (calcular) — la cuenta calculada.","¡La cuenta, por favor!"],
   ["lecker","delicioso","Das schmeckt lecker!","Corta y pegajosa, fácil de repetir.","¡Esto sabe delicioso!"],
   ["allergisch gegen","alérgico a","Ich bin allergisch gegen Nüsse.","'Allergisch' se parece mucho a 'alérgico'.","Soy alérgico a las nueces."],
   ["Tisch für zwei","Mesa para dos","Ein Tisch für zwei, bitte.","'Tisch' = mesa, 'zwei' = dos (suena 'tsvái').","Una mesa para dos, por favor."]],
  viajes:[["Flughafen","Aeropuerto","Der Flughafen ist weit.","'Flug' (vuelo) + 'Hafen' (puerto) = puerto de vuelo.","El aeropuerto está lejos."],
   ["Fahrkarte","Boleto","Wo ist meine Fahrkarte?","'Fahr' (viajar) + 'Karte' (tarjeta) = tarjeta de viaje.","¿Dónde está mi boleto?"],
   ["Gepäck","Equipaje","Mein Gepäck ist schwer.","Corta, suena a 'guepék'.","Mi equipaje pesa mucho."],
   ["Reisepass","Pasaporte","Ich brauche meinen Reisepass.","'Reise' (viaje) + 'Pass' (pase) = pase de viaje.","Necesito mi pasaporte."],
   ["Wo ist...?","¿Dónde está...?","Wo ist das Hotel?","'Wo' suena a 'vo', pregunta corta de lugar.","¿Dónde está el hotel?"],
   ["Wie lange dauert es?","¿Cuánto tiempo dura?","Wie lange dauert der Flug?","'Dauert' viene de durar — 'cuánto dura'.","¿Cuánto dura el vuelo?"]],
  emergencias:[["Hilfe!","¡Ayuda!","Hilfe! Bitte!","Corta, suena a 'jílfe' — fácil de gritar.","¡Ayuda! ¡Por favor!"],
   ["Rufen Sie die Polizei","Llame a la policía","Bitte, rufen Sie die Polizei!","'Polizei' es casi idéntica a 'policía'.","Por favor, ¡llame a la policía!"],
   ["Ich brauche einen Arzt","Necesito un médico","Ich brauche sofort einen Arzt.","'Arzt' suena a 'arst' — corto y directo.","Necesito un médico ahora mismo."],
   ["Feuer!","¡Fuego!","Feuer! Raus hier!","Suena a 'fóier' — parecido a 'fire' en inglés.","¡Fuego! ¡Sal de aquí!"],
   ["Ich habe mich verlaufen","Estoy perdido","Entschuldigung, ich habe mich verlaufen.","'Verlaufen' = perderse caminando (laufen = caminar).","Disculpe, estoy perdido."],
   ["Krankenwagen","Ambulancia","Rufen Sie einen Krankenwagen!","'Kranken' (enfermo) + 'Wagen' (carro) = carro de enfermo.","¡Llame una ambulancia!"]],
  familia:[["Mutter","Madre","Das ist meine Mutter.","Suena a 'muter', parecida a 'mother' en inglés.","Esta es mi madre."],
   ["Vater","Padre","Mein Vater arbeitet viel.","Se parece a 'father' en inglés, cambia la 'f' por 'v'.","Mi padre trabaja mucho."],
   ["Bruder","Hermano","Ich habe einen Bruder.","Parecida a 'brother' en inglés.","Tengo un hermano."],
   ["Schwester","Hermana","Meine Schwester ist jünger.","Empieza con 'sch', parecida a 'sister' en inglés.","Mi hermana es menor."],
   ["Kinder","Hijos","Wir haben zwei Kinder.","De aquí viene 'kindergarten' (jardín de niños), palabra que ya conoces.","Tenemos dos hijos."],
   ["Ehemann","Esposo","Mein Ehemann ist Arzt.","'Ehe' = matrimonio, 'Mann' = hombre — el hombre del matrimonio.","Mi esposo es médico."],
   ["Großmutter","Abuela","Meine Großmutter wohnt bei uns.","'Groß' = grande, 'Mutter' = madre — la madre grande.","Mi abuela vive con nosotros."]],
  salud:[["Arzt","Doctor","Ich muss zum Arzt.","Corta, suena a 'arst'.","Tengo que ir al médico."],
   ["Termin","Cita","Ich habe einen Termin um 15 Uhr.","Se parece a 'término', un momento fijado.","Tengo una cita a las 3pm."],
   ["Kopfschmerzen","Dolor de cabeza","Ich habe Kopfschmerzen.","'Kopf' = cabeza, 'Schmerzen' = dolores.","Tengo dolor de cabeza."],
   ["Medizin","Medicina","Nimm diese Medizin zweimal täglich.","Casi idéntica al español.","Toma esta medicina dos veces al día."],
   ["Apotheke","Farmacia","Die Apotheke ist geöffnet.","Suena a 'apoteke', parecida a 'botica' antigua.","La farmacia está abierta."],
   ["Mir geht es schlecht","Me siento mal","Mir geht es heute schlecht.","'Schlecht' = mal, literal 'me va mal'.","Me siento mal hoy."],
   ["Fieber","Fiebre","Sie hat Fieber.","Parecida a 'fever' en inglés.","Ella tiene fiebre."]],
  tecnologia:[["Telefon","Teléfono","Mein Telefon ist kaputt.","Casi idéntica al español.","Mi teléfono está roto."],
   ["Computer","Computadora","Ich arbeite an meinem Computer.","Igual que en inglés y español.","Trabajo en mi computadora."],
   ["Passwort","Contraseña","Ich habe mein Passwort vergessen.","'Pass' (pase) + 'Wort' (palabra) = palabra de paso.","Olvidé mi contraseña."],
   ["Internet","Internet","Das Internet ist langsam.","Idéntica en todos los idiomas.","El internet está lento."],
   ["App","Aplicación","Lade diese App herunter.","Igual que en español.","Descarga esta aplicación."],
   ["Ladegerät","Cargador","Hast du ein Ladegerät?","'Laden' = cargar, 'Gerät' = aparato.","¿Tienes un cargador?"],
   ["WLAN","Wifi","Wie ist das WLAN-Passwort?","Así le dicen los alemanes al wifi (Wireless LAN).","¿Cuál es la contraseña del wifi?"]],
  clima:[["sonnig","Soleado","Heute ist es sonnig.","'Sonne' = sol.","Hoy está soleado."],
   ["regnerisch","Lluvioso","Es ist regnerisch draußen.","'Regen' = lluvia.","Está lloviendo afuera."],
   ["kalt","Frío","Es ist heute sehr kalt.","Corta y fácil, suena a 'kalt' de 'helado'.","Hace mucho frío hoy."],
   ["heiß","Caliente","Es ist heiß im Sommer.","Suena a 'jais', imagina algo muy caliente.","Hace calor en verano."],
   ["Regenschirm","Paraguas","Bring einen Regenschirm mit.","'Regen' (lluvia) + 'Schirm' (sombrilla).","Trae un paraguas."],
   ["Schnee","Nieve","Es schneit.","Corta, suena parecida a 'esnéi'.","Está nevando."],
   ["Wind","Viento","Es gibt viel Wind.","Igual que en español e inglés.","Hay mucho viento."]]
 },
 pt:{
  saludos:[["Olá","Hola","Olá, tudo bem?","Casi idéntica al español, muy fácil.","Hola, ¿todo bien?"],
   ["Bom dia","Buenos días","Bom dia! Como você está?","'Bom' = bueno, 'dia' = día, igual que en español.","¡Buenos días! ¿Cómo estás?"],
   ["Como vai?","¿Cómo estás?","Oi, como vai?","Casi igual al español 'cómo va'.","Hola, ¿cómo estás?"],
   ["Prazer em conhecê-lo","Mucho gusto","Prazer em conhecê-lo, sou a Kate.","'Prazer' = placer, 'conhecer' = conocer.","Mucho gusto, soy Kate."],
   ["Até mais","Hasta luego","Até mais, tchau!","'Até' = hasta, casi igual al español.","Hasta luego, ¡chao!"],
   ["Tchau","Adiós","Tchau, até amanhã!","Prestado del italiano 'ciao', se pronuncia igual.","Chao, ¡hasta mañana!"]],
  compras:[["Quanto custa?","¿Cuánto cuesta?","Quanto custa esta camisa?","Casi idéntica al español 'cuánto cuesta'.","¿Cuánto cuesta esta camisa?"],
   ["Recibo","Recibo","Posso ter o recibo?","Idéntica al español.","¿Me da el recibo?"],
   ["Dinheiro","Efectivo/dinero","Vou pagar em dinheiro.","Se parece a 'dinero', solo cambia la terminación.","Voy a pagar en efectivo."],
   ["Cartão de crédito","Tarjeta de crédito","Vocês aceitam cartão de crédito?","'Cartão' = tarjeta (cartón), fácil de asociar.","¿Aceptan tarjeta de crédito?"],
   ["Desconto","Descuento","Tem desconto hoje?","Casi idéntica al español.","¿Hay descuento hoy?"],
   ["Carrinho de compras","Carrito de compras","Preciso de um carrinho.","'Carrinho' = carrito, diminutivo fácil de reconocer.","Necesito un carrito."]],
  trabajo:[["Reunião","Reunión","Temos uma reunião às 15h.","Muy parecida al español, solo cambia la terminación.","Tenemos una reunión a las 3pm."],
   ["Prazo","Fecha límite/plazo","O prazo é sexta-feira.","Idéntica a 'plazo' en español.","La fecha límite es el viernes."],
   ["Colega","Colega","Meu colega enviou o e-mail.","Idéntica al español.","Mi colega envió el correo."],
   ["E-mail","Correo electrónico","Me manda um e-mail.","Igual que en español.","Envíame un correo."],
   ["Agenda","Horario/agenda","Qual é a sua agenda hoje?","Idéntica al español.","¿Cuál es tu agenda hoy?"],
   ["Chefe","Jefe","Meu chefe é gentil.","Muy parecida a 'jefe', cambia la 'j' por 'ch'.","Mi jefe es amable."]],
  comida:[["Água","Agua","Posso ter água?","Casi idéntica, solo el acento cambia.","¿Me da agua?"],
   ["Pão","Pan","Eu queria pão.","Sonido nasal 'ão' — imagina decir 'pan' tapándote la nariz.","Yo quisiera pan."],
   ["A conta, por favor","La cuenta, por favor","A conta, por favor!","Casi idéntica al español.","¡La cuenta, por favor!"],
   ["delicioso","delicioso","Isso está delicioso!","Idéntica al español.","¡Esto está delicioso!"],
   ["alérgico a","alérgico a","Sou alérgico a nozes.","Idéntica al español.","Soy alérgico a las nueces."],
   ["Mesa para dois","Mesa para dos","Uma mesa para dois, por favor.","Casi idéntica, 'dois' = dos.","Una mesa para dos, por favor."]],
  viajes:[["Aeroporto","Aeropuerto","O aeroporto é longe.","Casi idéntica al español.","El aeropuerto está lejos."],
   ["Passagem","Boleto/pasaje","Onde está minha passagem?","Idéntica a 'pasaje' en español.","¿Dónde está mi pasaje?"],
   ["Bagagem","Equipaje","Minha bagagem é pesada.","Se parece a 'bagaje' en español.","Mi equipaje pesa mucho."],
   ["Passaporte","Pasaporte","Preciso do meu passaporte.","Casi idéntica al español.","Necesito mi pasaporte."],
   ["Onde fica...?","¿Dónde está...?","Onde fica o hotel?","'Onde' = dónde, muy parecida.","¿Dónde queda el hotel?"],
   ["Quanto tempo demora?","¿Cuánto tiempo tarda?","Quanto tempo demora o voo?","'Demora' = tarda, casi idéntica al español.","¿Cuánto tarda el vuelo?"]],
  emergencias:[["Socorro!","¡Ayuda!","Socorro! Me ajude!","Idéntica al español.","¡Auxilio! ¡Ayúdame!"],
   ["Chame a polícia","Llame a la policía","Por favor, chame a polícia!","'Polícia' idéntica al español.","Por favor, ¡llame a la policía!"],
   ["Preciso de um médico","Necesito un médico","Preciso de um médico agora.","Casi idéntica al español.","Necesito un médico ahora."],
   ["Incêndio!","¡Incendio!","Incêndio! Saia!","Idéntica al español.","¡Incendio! ¡Salga!"],
   ["Estou perdido","Estoy perdido","Desculpe, estou perdido.","Idéntica al español.","Disculpe, estoy perdido."],
   ["Ambulância","Ambulancia","Chame uma ambulância!","Casi idéntica al español.","¡Llame una ambulancia!"]],
  familia:[["Mãe","Madre","Esta é minha mãe.","Muy parecida a 'madre', con sonido nasal al final.","Esta es mi madre."],
   ["Pai","Padre","Meu pai trabalha muito.","Parecida a 'padre'.","Mi padre trabaja mucho."],
   ["Irmão","Hermano","Tenho um irmão.","Parecida a 'hermano', con sonido nasal.","Tengo un hermano."],
   ["Irmã","Hermana","Minha irmã é mais nova.","Versión femenina de 'irmão'.","Mi hermana es menor."],
   ["Filhos","Hijos","Temos dois filhos.","Parecida a 'hijos', cambia la 'h' por 'f'.","Tenemos dos hijos."],
   ["Marido","Esposo","Meu marido é médico.","Corta y directa, fácil de recordar.","Mi esposo es médico."],
   ["Avó","Abuela","Minha avó mora conosco.","Parecida a 'abuela' sin la 'b' y la 'l'.","Mi abuela vive con nosotros."]],
  salud:[["Médico","Doctor","Preciso ver um médico.","Idéntica al español.","Necesito ver a un médico."],
   ["Consulta","Cita","Tenho uma consulta às 15h.","Idéntica al español.","Tengo una cita a las 3pm."],
   ["Dor de cabeça","Dolor de cabeza","Estou com dor de cabeça.","Casi idéntica al español.","Tengo dolor de cabeza."],
   ["Remédio","Medicina","Tome este remédio duas vezes ao dia.","Parecida a 'remedio' en español.","Toma esta medicina dos veces al día."],
   ["Farmácia","Farmacia","A farmácia está aberta.","Idéntica al español.","La farmacia está abierta."],
   ["Estou me sentindo mal","Me siento mal","Estou me sentindo mal hoje.","Casi idéntica al español.","Me siento mal hoy."],
   ["Febre","Fiebre","Ela está com febre.","Idéntica al español.","Ella tiene fiebre."]],
  tecnologia:[["Telefone","Teléfono","Meu telefone quebrou.","Casi idéntica al español.","Mi teléfono se rompió."],
   ["Computador","Computadora","Eu trabalho no computador.","Casi idéntica al español.","Trabajo en la computadora."],
   ["Senha","Contraseña","Esqueci minha senha.","Corta, distinta al español pero fácil de repetir.","Olvidé mi contraseña."],
   ["Internet","Internet","A internet está lenta.","Idéntica en todos los idiomas.","El internet está lento."],
   ["Aplicativo","Aplicación","Baixe este aplicativo.","Parecida a 'aplicativo', ya usado en español latino.","Descarga esta aplicación."],
   ["Carregador","Cargador","Você tem um carregador?","Casi idéntica al español.","¿Tienes un cargador?"],
   ["Wifi","Wifi","Qual é a senha do wifi?","Idéntica en todos los idiomas.","¿Cuál es la contraseña del wifi?"]],
  clima:[["Ensolarado","Soleado","Hoje está ensolarado.","'Sol' está dentro de la palabra.","Hoy está soleado."],
   ["Chuvoso","Lluvioso","Está chuvoso lá fora.","'Chuva' = lluvia.","Está lloviendo afuera."],
   ["Frio","Frío","Está muito frio hoje.","Idéntica al español.","Hace mucho frío hoy."],
   ["Quente","Caliente","Está quente no verão.","Corta, fácil de repetir.","Hace calor en verano."],
   ["Guarda-chuva","Paraguas","Leve um guarda-chuva.","'Guarda' (protege) + 'chuva' (lluvia) = protege de la lluvia.","Lleva un paraguas."],
   ["Neve","Nieve","Está nevando.","Parecida a 'nieve'.","Está nevando."],
   ["Vento","Viento","Tem muito vento.","Idéntica al español.","Hay mucho viento."]]
 },
 it:{
  saludos:[["Ciao","Hola/Chao","Ciao, come stai?","Ya la usamos en español como 'chao' para despedirnos.","Hola, ¿cómo estás?"],
   ["Buongiorno","Buenos días","Buongiorno a tutti!","'Buon' = bueno, 'giorno' = día.","¡Buenos días a todos!"],
   ["Come stai?","¿Cómo estás?","Ciao, come stai?","'Come' suena a 'cóme', pregunta de estado.","Hola, ¿cómo estás?"],
   ["Piacere di conoscerti","Mucho gusto","Piacere di conoscerti, sono Kate.","'Piacere' = placer, casi idéntica al español.","Mucho gusto, soy Kate."],
   ["A dopo","Hasta luego","A dopo, ciao!","'Dopo' = después, corta y fácil.","Hasta luego, ¡chao!"],
   ["Arrivederci","Adiós","Arrivederci, a presto!","'Ri-vedere' = volver a ver, como el alemán 'Wiedersehen'.","Adiós, ¡hasta pronto!"]],
  compras:[["Quanto costa?","¿Cuánto cuesta?","Quanto costa questa maglietta?","Casi idéntica al español.","¿Cuánto cuesta esta camiseta?"],
   ["Scontrino","Recibo","Posso avere lo scontrino?","'Sconto' = descuento, el recibo confirma lo que pagaste.","¿Me da el recibo?"],
   ["Contanti","Efectivo","Pago in contanti.","Se parece a 'contar' dinero en efectivo.","Pago en efectivo."],
   ["Carta di credito","Tarjeta de crédito","Accettate carta di credito?","Casi idéntica al español.","¿Aceptan tarjeta de crédito?"],
   ["Sconto","Descuento","C'è uno sconto oggi?","Muy parecida al español 'descuento'.","¿Hay descuento hoy?"],
   ["Carrello","Carrito de compras","Ho bisogno di un carrello.","Se parece a 'carro' con diminutivo.","Necesito un carrito."]],
  trabajo:[["Riunione","Reunión","Abbiamo una riunione alle 15.","Muy parecida al español 'reunión'.","Tenemos una reunión a las 3pm."],
   ["Scadenza","Fecha límite","La scadenza è venerdì.","'Scadere' = vencer, como una fecha que vence.","La fecha límite es el viernes."],
   ["Collega","Colega","Il mio collega ha inviato l'e-mail.","Idéntica al español.","Mi colega envió el correo."],
   ["E-mail","Correo electrónico","Mandami una e-mail.","Igual que en español.","Envíame un correo."],
   ["Programma","Horario/agenda","Qual è il tuo programma oggi?","Idéntica al español 'programa'.","¿Cuál es tu agenda hoy?"],
   ["Capo","Jefe","Il mio capo è gentile.","Corta, 'capo' = cabeza/jefe, como en italiano-español mafioso conocido.","Mi jefe es amable."]],
  comida:[["Acqua","Agua","Posso avere dell'acqua?","Muy parecida al español, cambia la 'g' por 'c' doble.","¿Me da agua?"],
   ["Pane","Pan","Vorrei del pane.","Casi idéntica al español.","Quisiera pan."],
   ["Il conto, per favore","La cuenta, por favor","Il conto, per favore!","'Conto' = cuenta, casi idéntica al español.","¡La cuenta, por favor!"],
   ["delizioso","delicioso","Questo è delizioso!","Casi idéntica al español.","¡Esto está delicioso!"],
   ["allergico a","alérgico a","Sono allergico alle noci.","Casi idéntica al español.","Soy alérgico a las nueces."],
   ["Tavolo per due","Mesa para dos","Un tavolo per due, per favore.","'Tavolo' = mesa, 'due' = dos.","Una mesa para dos, por favor."]],
  viajes:[["Aeroporto","Aeropuerto","L'aeroporto è lontano.","Casi idéntica al español.","El aeropuerto está lejos."],
   ["Biglietto","Boleto","Dov'è il mio biglietto?","Se parece a 'billete' en español.","¿Dónde está mi boleto?"],
   ["Bagaglio","Equipaje","Il mio bagaglio è pesante.","Se parece a 'bagaje' en español.","Mi equipaje pesa mucho."],
   ["Passaporto","Pasaporte","Ho bisogno del passaporto.","Casi idéntica al español.","Necesito el pasaporte."],
   ["Dov'è...?","¿Dónde está...?","Dov'è l'hotel?","'Dove' = dónde, muy parecida al español.","¿Dónde está el hotel?"],
   ["Quanto tempo ci vuole?","¿Cuánto tiempo toma?","Quanto tempo ci vuole per arrivare?","'Ci vuole' = se necesita/toma.","¿Cuánto tiempo toma llegar?"]],
  emergencias:[["Aiuto!","¡Ayuda!","Aiuto! Per favore!","Corta, fácil de gritar en una emergencia.","¡Ayuda! ¡Por favor!"],
   ["Chiama la polizia","Llama a la policía","Per favore, chiama la polizia!","'Polizia' idéntica al español.","Por favor, ¡llama a la policía!"],
   ["Ho bisogno di un medico","Necesito un médico","Ho bisogno di un medico subito.","'Medico' casi idéntica al español.","Necesito un médico ahora mismo."],
   ["Incendio!","¡Incendio!","Incendio! Esci!","Idéntica al español.","¡Incendio! ¡Sal!"],
   ["Mi sono perso","Estoy perdido","Scusi, mi sono perso.","Casi idéntica al español.","Disculpe, estoy perdido."],
   ["Ambulanza","Ambulancia","Chiama un'ambulanza!","Casi idéntica al español.","¡Llama una ambulancia!"]],
  familia:[["Madre","Madre","Questa è mia madre.","Idéntica al español.","Esta es mi madre."],
   ["Padre","Padre","Mio padre lavora molto.","Idéntica al español.","Mi padre trabaja mucho."],
   ["Fratello","Hermano","Ho un fratello.","Parecida a 'fraternal' en español.","Tengo un hermano."],
   ["Sorella","Hermana","Mia sorella è più giovane.","Parecida a 'sorority' en inglés.","Mi hermana es menor."],
   ["Figli","Hijos","Abbiamo due figli.","Parecida a 'filial' en español.","Tenemos dos hijos."],
   ["Marito","Esposo","Mio marito è medico.","Corta y directa, fácil de recordar.","Mi esposo es médico."],
   ["Nonna","Abuela","Mia nonna vive con noi.","Corta y tierna, fácil de repetir.","Mi abuela vive con nosotros."]],
  salud:[["Medico","Doctor","Devo vedere un medico.","Idéntica al español.","Debo ver a un médico."],
   ["Appuntamento","Cita","Ho un appuntamento alle 15.","Parecida a 'apuntamiento/apuntar' una cita.","Tengo una cita a las 3pm."],
   ["Mal di testa","Dolor de cabeza","Ho mal di testa.","'Mal' = dolor/mal, 'testa' = cabeza.","Tengo dolor de cabeza."],
   ["Medicina","Medicina","Prendi questa medicina due volte al giorno.","Idéntica al español.","Toma esta medicina dos veces al día."],
   ["Farmacia","Farmacia","La farmacia è aperta.","Idéntica al español.","La farmacia está abierta."],
   ["Mi sento male","Me siento mal","Mi sento male oggi.","Casi idéntica al español.","Me siento mal hoy."],
   ["Febbre","Fiebre","Ha la febbre.","Parecida a 'fiebre', con doble b.","Tiene fiebre."]],
  tecnologia:[["Telefono","Teléfono","Il mio telefono è rotto.","Casi idéntica al español.","Mi teléfono está roto."],
   ["Computer","Computadora","Lavoro al computer.","Igual que en inglés.","Trabajo en la computadora."],
   ["Password","Contraseña","Ho dimenticato la password.","Igual que en inglés.","Olvidé la contraseña."],
   ["Internet","Internet","Internet è lento.","Idéntica en todos los idiomas.","El internet está lento."],
   ["App","Aplicación","Scarica questa app.","Igual que en inglés/español.","Descarga esta aplicación."],
   ["Caricabatterie","Cargador","Hai un caricabatterie?","'Carica' (carga) + 'batterie' (baterías).","¿Tienes un cargador?"],
   ["Wifi","Wifi","Qual è la password del wifi?","Idéntica en todos los idiomas.","¿Cuál es la contraseña del wifi?"]],
  clima:[["Soleggiato","Soleado","Oggi è soleggiato.","'Sole' = sol.","Hoy está soleado."],
   ["Piovoso","Lluvioso","È piovoso fuori.","'Pioggia' = lluvia.","Está lloviendo afuera."],
   ["Freddo","Frío","Fa molto freddo oggi.","Parecida a 'frío', con doble d.","Hace mucho frío hoy."],
   ["Caldo","Caliente","Fa caldo in estate.","¡Ojo, falso amigo! En español 'caldo' es sopa; en italiano significa 'caliente'.","Hace calor en verano."],
   ["Ombrello","Paraguas","Porta un ombrello.","Parecida a 'umbrella' en inglés.","Lleva un paraguas."],
   ["Neve","Nieve","Sta nevicando.","Casi idéntica al español.","Está nevando."],
   ["Vento","Viento","C'è molto vento.","Casi idéntica al español.","Hay mucho viento."]]
 }
};

/* IMPORTANTE: solo agregar situaciones nuevas AL FINAL. El progreso guardado (p.lang[id].lesson)
   es un índice sobre este arreglo — insertar o reordenar cambiaría el significado de progreso ya
   guardado de usuarios reales. */
const LANG_SITUATIONS=["saludos","compras","trabajo","comida","viajes","emergencias","familia","salud","tecnologia","clima"];
const LANG_SITUATION_LABEL={saludos:"👋 Saludos",compras:"🛒 Compras",trabajo:"💼 Trabajo",comida:"🍽️ Comida",viajes:"✈️ Viajes",emergencias:"🚨 Emergencias",familia:"👨‍👩‍👧 Familia",salud:"🏥 Salud",tecnologia:"💻 Tecnología",clima:"☀️ Clima"};

/* dos reglas gramaticales por nivel CEFR (índice 0=A1 … 5=C2), comparadas con el español.
   Se rotan por lección (st.lesson % variantes) para que el "tema de hoy" no se repita siempre
   igual dentro del mismo nivel (con 10 lecciones por nivel, una sola regla se sentía repetitiva). */
const LANG_GRAMMAR_SEED={
 en:[
  [{rule:"El verbo 'to be' (ser/estar)",explicacion:"En inglés un solo verbo (to be) cubre 'ser' Y 'estar': I am, you are, he/she is, we are, they are.",compara:"El español usa DOS verbos (ser/estar) para lo que el inglés hace con uno solo — más simple, solo hay que aprender cuándo usarlo."},
   {rule:"Plural de sustantivos (-s)",explicacion:"La mayoría de sustantivos suman '-s' para el plural: book→books, car→cars.",compara:"El español también usa -s/-es para el plural, muy parecido — pero en inglés la palabra casi nunca cambia de raíz como sí pasa a veces en español."}],
  [{rule:"Pasado simple regular (-ed)",explicacion:"Para hablar del pasado, la mayoría de verbos suman '-ed': play→played, work→worked.",compara:"Es parecido al pretérito español (jugué, trabajé), pero en inglés el verbo NO cambia según quién habla: I played, she played (igual)."},
   {rule:"Comparativos y superlativos",explicacion:"Con -er/-est (big→bigger→biggest) o more/most para palabras largas (expensive→more expensive).",compara:"El español usa 'más' siempre (más grande, el más grande); el inglés a veces cambia la palabra en vez de agregar 'más'."}],
  [{rule:"Presente perfecto (have + participio)",explicacion:"'I have eaten' conecta algo pasado con el presente (ya comí, y eso importa ahora).",compara:"No existe una forma idéntica en español; se parece más a 'he comido', pero el inglés lo usa mucho más seguido que el español."},
   {rule:"Primer condicional (if + presente, will)",explicacion:"'If it rains, I will stay home' describe algo que probablemente pase.",compara:"Muy parecido al español 'si llueve, me quedaré' — misma lógica, con 'will' en vez de la terminación '-ré'."}],
  [{rule:"Condicional con 'would'",explicacion:"'I would go' expresa algo hipotético: lo que harías si...",compara:"Funciona como la terminación '-ía' del español (iría, comería) — mismo concepto, distinta forma."},
   {rule:"Segundo condicional (if + pasado, would)",explicacion:"'If I had money, I would travel' describe algo hipotético improbable ahora.",compara:"Como el español 'si tuviera dinero, viajaría' — misma estructura de hipótesis irreal."}],
  [{rule:"Voz pasiva (be + participio)",explicacion:"'The email was sent' pone el foco en la acción, no en quién la hizo.",compara:"El español suele usar 'se + verbo' (se envió el correo) para lo mismo — dos formas, misma idea."},
   {rule:"Cláusulas relativas (who, which, that)",explicacion:"'The man who called is my boss' añade información sobre un sustantivo.",compara:"Como el español 'que' (el hombre que llamó), pero el inglés distingue 'who' (personas) de 'which' (cosas)."}],
  [{rule:"Estilo indirecto (reported speech)",explicacion:"Al repetir lo que alguien dijo, los tiempos verbales 'retroceden': 'I am tired' → 'She said she was tired'.",compara:"En español también cambiamos el tiempo al reportar ('dijo que estaba cansada'), la lógica es la misma."},
   {rule:"Inversión enfática",explicacion:"'Never have I seen...' invierte el orden normal para dar énfasis formal o literario.",compara:"No existe en español; es un recurso especial para sonar más formal o dramático, cambiando el orden sujeto-verbo."}]
 ],
 de:[
  [{rule:"El verbo va en segunda posición",explicacion:"En alemán el verbo conjugado SIEMPRE ocupa el segundo lugar de la oración, sin importar qué vaya primero: 'Heute gehe ich' (Hoy voy yo).",compara:"En español el orden es más libre; en alemán esta regla es fija y ayuda a entender frases largas."},
   {rule:"Sustantivos con género (der/die/das)",explicacion:"Cada sustantivo tiene un artículo fijo: der Mann, die Frau, das Kind.",compara:"El español tiene género pero solo dos (el/la); el alemán tiene tres, y hay que memorizar el artículo de cada palabra."}],
  [{rule:"Casos: Nominativ vs Akkusativ",explicacion:"El artículo cambia según si la palabra es sujeto (der Mann) o complemento directo (den Mann).",compara:"El español no cambia el artículo según la función en la oración — esto es lo más nuevo del alemán para un hispanohablante."},
   {rule:"Plural de sustantivos (varias formas)",explicacion:"El plural puede terminar en -e, -er, -en o -s según la palabra: Kind→Kinder, Auto→Autos.",compara:"El español casi siempre usa -s/-es; el alemán tiene varias formas irregulares que se aprenden palabra por palabra."}],
  [{rule:"Verbos modales + verbo al final",explicacion:"Con 'können, müssen, wollen' el verbo principal se va al FINAL: 'Ich kann Deutsch sprechen' (Puedo alemán hablar).",compara:"En español el orden es sujeto-verbo-verbo (puedo hablar), en alemán se separan y el segundo verbo va al final."},
   {rule:"Perfekt en conversación (haben/sein + participio)",explicacion:"Para hablar del pasado al conversar se usa 'haben' o 'sein' + participio: 'Ich habe gegessen' (comí/he comido).",compara:"Como el pretérito perfecto compuesto español 'he comido', pero el alemán lo usa incluso para historias del pasado, no solo lo muy reciente."}],
  [{rule:"El caso Dativ (a quién)",explicacion:"Dativ indica a quién se dirige la acción: 'Ich gebe dem Mann das Buch' (le doy el libro al hombre).",compara:"El español no tiene esta marca en el artículo; usamos 'a/le' — el alemán lo marca cambiando der→dem."},
   {rule:"Oraciones con 'weil'/'dass' (verbo al final)",explicacion:"En oraciones subordinadas con 'weil' (porque) o 'dass' (que), el verbo se va al final: 'Ich bleibe, weil ich müde bin'.",compara:"El español no mueve el verbo al final con 'porque/que'; el alemán sí, por eso las frases largas suenan 'al revés'."}],
  [{rule:"Konjunktiv II (el irreal/condicional)",explicacion:"'Ich würde gehen' o 'Ich wäre' expresan algo hipotético o cortés.",compara:"Funciona como el español 'iría' o 'si tuviera' — incluso se usa para pedir las cosas con más cortesía."},
   {rule:"Konjunktiv I (discurso indirecto formal)",explicacion:"Se usa una forma verbal especial para citar lo que otra persona dijo, sobre todo en noticias: 'Er sagte, er komme'.",compara:"Como el español 'dijo que él vendría', pero el alemán tiene una conjugación específica solo para citar."}],
  [{rule:"Voz pasiva con 'werden'",explicacion:"'Die E-Mail wird gesendet' (El correo es enviado) usa 'werden' + participio.",compara:"Parecido a la pasiva del español ('es enviado'), pero el alemán usa 'werden' (llegar a ser) en vez de 'ser'."},
   {rule:"Construcciones de participio (formal/escrito)",explicacion:"Resumen una oración subordinada en una frase corta con participio, común en textos formales.",compara:"No tiene equivalente directo en español; el español preferiría una oración completa con 'que' en vez de acortarla así."}]
 ],
 pt:[
  [{rule:"Ser vs. Estar",explicacion:"Igual que en español, el portugués distingue 'ser' (permanente) de 'estar' (temporal): Eu sou / Eu estou.",compara:"Esta es la transferencia MÁS fácil del portugués: la regla es casi idéntica a la del español."},
   {rule:"Plural con -s (y cambios en -ão)",explicacion:"La mayoría suma -s (casa→casas), pero las palabras en -ão cambian: pão→pães.",compara:"El español usa -s/-es también, pero el portugués tiene cambios especiales en palabras terminadas en -ão que hay que memorizar."}],
  [{rule:"Pretérito perfeito (-ei/-ou)",explicacion:"Falei (hablé), Comeu (comió) — terminaciones regulares para el pasado simple.",compara:"Muy parecido al pretérito español (hablé, comió), solo cambian un poco las terminaciones."},
   {rule:"Presente continuo (estar + gerúndio)",explicacion:"'Estou falando' (estoy hablando) describe una acción en curso.",compara:"Casi idéntico al español 'estoy hablando' — otra transferencia fácil entre los dos idiomas."}],
  [{rule:"'Você' se conjuga como 'él/ella'",explicacion:"Aunque 'você' significa 'tú', se conjuga en tercera persona: 'Você fala' (no 'você falas').",compara:"En español 'tú hablas' usa segunda persona; en portugués 'você fala' usa la forma de 'él/ella habla' — la trampa más común para hispanohablantes."},
   {rule:"Imperativo (dar órdenes)",explicacion:"Para pedir o mandar algo: 'Fale mais devagar' (habla más despacio).",compara:"Parecido al imperativo español, pero cambia un poco según se use 'tu' o 'você' para dar la orden."}],
  [{rule:"Futuro do subjuntivo",explicacion:"Se usa tras 'quando' o 'se' para eventos futuros hipotéticos: 'Quando eu chegar, te ligo'.",compara:"El español usa presente de subjuntivo para esto ('cuando llegue'); el portugués tiene un tiempo verbal propio para el futuro hipotético."},
   {rule:"Por vs. Para",explicacion:"'Por' indica causa o medio (por isso, por telefone); 'para' indica destino o finalidad (para você, para trabalhar).",compara:"La misma distinción confusa que existe en español (por=causa, para=destino) — si ya la manejas en español, aplica casi igual en portugués."}],
  [{rule:"Colocación del pronombre (o/lhe)",explicacion:"El pronombre puede ir antes o después del verbo según la oración: 'Ele me viu' vs 'Viu-me'.",compara:"El español siempre pone el pronombre antes en estos casos ('me vio'); el portugués es más flexible."},
   {rule:"Voz pasiva con 'ser' + participio",explicacion:"'A ponte foi construída' (El puente fue construido) — foco en la acción, no en quién la hizo.",compara:"Igual que el español 'fue construido' — transferencia directa, casi sin cambios."}],
  [{rule:"Subjuntivo en cláusulas complejas",explicacion:"'Espero que você venha' usa subjuntivo tras expresiones de deseo o duda.",compara:"Es prácticamente igual al subjuntivo español ('espero que vengas') — otra transferencia fácil."},
   {rule:"Concordância verbal con sujetos colectivos",explicacion:"Con sujetos como 'a maioria', el verbo puede ir en singular o plural según el matiz: 'a maioria disse/disseram'.",compara:"Como el español, hay reglas especiales cuando el sujeto es un grupo — matices finos que se aprenden con la lectura y la práctica."}]
 ],
 it:[
  [{rule:"Artículos determinativos (il/lo/la/i/gli/le)",explicacion:"El artículo 'el' cambia según la letra inicial de la palabra: il libro, lo studente, la casa.",compara:"El español solo tiene 'el/la'; el italiano tiene más variantes que dependen del sonido inicial — hay que memorizar el patrón."},
   {rule:"Plural de sustantivos (cambia la vocal final)",explicacion:"El plural se forma cambiando la última letra: libro→libri, casa→case.",compara:"El español agrega -s; el italiano CAMBIA la última letra, un patrón distinto que hay que memorizar palabra por palabra."}],
  [{rule:"Passato prossimo (avere/essere + participio)",explicacion:"'Ho mangiato' (he comido) o 'Sono andato' (he ido) — dos verbos auxiliares posibles según el verbo.",compara:"Se parece al pretérito perfecto compuesto español ('he comido'), pero el italiano a veces usa 'essere' (ser) en vez de 'haber'."},
   {rule:"Preposiciones simples (a, di, da, in, su)",explicacion:"Cada una tiene un uso propio: 'vado a Roma', 'vengo da Milano', 'sono di Napoli'.",compara:"Parecidas a sus equivalentes en español (a, de, desde, en, sobre) pero no siempre coinciden exactamente en el uso."}],
  [{rule:"Preposiciones articuladas (nel, sulla, dal)",explicacion:"La preposición se fusiona con el artículo: in + il = nel, su + la = sulla.",compara:"El español mantiene 'en el, sobre la' separados; el italiano los junta en una sola palabra."},
   {rule:"Imperativo informal (tu)",explicacion:"Para dar órdenes directas a alguien cercano: 'Parla più piano' (habla más despacio).",compara:"Parecido al imperativo español informal (habla→parla), mismo concepto de dar órdenes directas."}],
  [{rule:"Congiuntivo presente",explicacion:"Se usa tras 'credo che, penso che' para expresar opinión o duda: 'Penso che sia vero'.",compara:"Funciona igual que el subjuntivo español tras 'creo que, pienso que' — transferencia bastante directa."},
   {rule:"Pronomi combinati (me lo, te lo)",explicacion:"Dos pronombres se combinan y cambian de forma: 'me lo dai' (me lo das).",compara:"El español también combina pronombres (dámelo); el italiano los junta de forma parecida, con algunos cambios de ortografía."}],
  [{rule:"Condizionale composto",explicacion:"'Avrei fatto' (habría hecho) expresa algo que no pasó pero pudo pasar.",compara:"Es exactamente el mismo concepto que el español 'habría hecho', solo cambia la forma del verbo."},
   {rule:"Discorso indiretto",explicacion:"Al reportar lo que alguien dijo, los tiempos verbales cambian: 'Ha detto che sarebbe venuto'.",compara:"Igual que el español al reportar lo que alguien dijo, los tiempos 'retroceden' de la misma manera."}],
  [{rule:"Periodo ipotetico (se + congiuntivo)",explicacion:"'Se avessi tempo, viaggerei' (Si tuviera tiempo, viajaría) — condición irreal.",compara:"Calca casi perfecto la estructura española 'si tuviera... viajaría' — misma lógica, distinta conjugación."},
   {rule:"Gerundio con valor causal/temporal",explicacion:"'Lavorando duro, ha ottenuto...' (Trabajando duro, logró...) expresa causa o tiempo sin conjunción.",compara:"Como el español 'trabajando duro, logró...' — el gerundio expresa causa o tiempo sin necesitar una palabra de conexión."}]
 ]
};

/* sonidos que no existen (o suenan distinto) en español, comparados para pronunciarlos bien */
const LANG_PRONUNCIATION={
 en:[
  {sonido:"th (think, this)",compara:"No existe en español. Pon la punta de la lengua entre los dientes y sopla — no es la 'z' de Madrid, es más suave."},
  {sonido:"r inglesa (red, car)",compara:"La lengua NO toca el paladar ni se enrolla como en español — se curva hacia atrás sin tocar nada."},
  {sonido:"vocal corta i (ship) vs larga ee (sheep)",compara:"En español una 'i' siempre suena igual; en inglés la duración cambia el significado de la palabra."},
  {sonido:"h aspirada (hello, house)",compara:"En español la 'h' es muda; en inglés se sopla suave, como una 'j' débil."}
 ],
 de:[
  {sonido:"ü (müde, für)",compara:"Di 'u' pero con los labios en posición de 'i' (como redondear la boca diciendo 'i')."},
  {sonido:"ö (schön, hören)",compara:"Di 'e' pero con los labios redondeados como para decir 'o'."},
  {sonido:"ch suave (ich, nicht)",compara:"No es la 'ch' española de 'chico' — es un sonido más suave, entre 'j' y 'sh', casi silbado."},
  {sonido:"r alemana (rot, Reise)",compara:"Se pronuncia en la garganta (gutural), no se enrolla con la punta de la lengua como en español."}
 ],
 pt:[
  {sonido:"ão nasal (não, pão)",compara:"El aire sale por la nariz — el español nunca nasaliza vocales, así que hay que practicarlo aparte."},
  {sonido:"lh (mulher, trabalho)",compara:"Suena como la 'll' del español de Argentina o España (no como una 'l' sola)."},
  {sonido:"r inicial o rr (rato, carro)",compara:"Suena como la 'j' española fuerte (jota), no como una 'r' suave."},
  {sonido:"vocales nasales (bem, sim)",compara:"El español no nasaliza; en portugués la 'm/n' final nasaliza la vocal anterior sin pronunciarse fuerte."}
 ],
 it:[
  {sonido:"gli (famiglia, figlio)",compara:"Parecido a la 'll' española pero más suave y rápido, casi como decir 'li' pegado."},
  {sonido:"gn (gnocchi, bagno)",compara:"Suena exactamente como la 'ñ' española — gnocchi se pronuncia 'ñoki'."},
  {sonido:"consonantes dobles (penna vs pena)",compara:"El español no distingue esto; en italiano una consonante doble se pronuncia más larga y cambia el significado."},
  {sonido:"c/g antes de e-i (cena, gelato)",compara:"Suenan como 'ch/j' suave (che, yelato), distinto a la 'c/g' fuerte del español."}
 ]
};

/* frases conectoras genéricas para armar la conversación de respaldo sin clave de Gemini */
const LANG_PHRASES={
 en:{greet:"Hello!",howAreYou:"How are you?",imFine:"I'm fine, thanks.",whatsYourName:"What's your name?",myNameIs:"My name is",yes:"Yes",no:"No",please:"please",thanks:"Thank you",dontUnderstand:"I don't understand",canYouRepeat:"Can you repeat that?",goodbye:"Goodbye!"},
 de:{greet:"Hallo!",howAreYou:"Wie geht's?",imFine:"Mir geht's gut, danke.",whatsYourName:"Wie heißt du?",myNameIs:"Ich heiße",yes:"Ja",no:"Nein",please:"bitte",thanks:"Danke",dontUnderstand:"Ich verstehe nicht",canYouRepeat:"Kannst du das wiederholen?",goodbye:"Auf Wiedersehen!"},
 pt:{greet:"Olá!",howAreYou:"Como vai?",imFine:"Estou bem, obrigado.",whatsYourName:"Qual é o seu nome?",myNameIs:"Meu nome é",yes:"Sim",no:"Não",please:"por favor",thanks:"Obrigado",dontUnderstand:"Não entendo",canYouRepeat:"Pode repetir?",goodbye:"Tchau!"},
 it:{greet:"Ciao!",howAreYou:"Come stai?",imFine:"Sto bene, grazie.",whatsYourName:"Come ti chiami?",myNameIs:"Mi chiamo",yes:"Sì",no:"No",please:"per favore",thanks:"Grazie",dontUnderstand:"Non capisco",canYouRepeat:"Puoi ripetere?",goodbye:"Arrivederci!"}
};
